// LinguaFlow — 20 种 UI 语言完整翻译（DeepSeek API 生成）
// zh-CN, zh-TW, en, ja, ko, fr, de, es, pt, ru, ar, hi, th, vi, it, nl, pl, tr, id, sv
function T(z,t,e,j,k,f,d,s,p,r,a,h,T,v,i,n,l,u,b,c){return{'zh-CN':z,'zh-TW':t||z,en:e,ja:j,ko:k,fr:f||e,de:d||e,es:s||e,pt:p||e,ru:r||e,ar:a||e,hi:h||e,th:T||e,vi:v||e,it:i||e,nl:n||e,pl:l||e,tr:u||e,id:b||e,sv:c||e}}

const I18N = {
autoTranslate:T('自动翻译','自動翻譯','Auto Translate','自動翻訳','자동 번역','Auto Traduire','Auto-Übersetzung','Auto Traducir','Auto Traduzir','Автоперевод','ترجمة تلقائية','स्वतः अनुवाद','แปลอัตโนมัติ','Tự động dịch','Auto Traduci','Auto Vertalen','Auto tłumacz','Otomatik Çeviri','Terjemahan Otomatis','Autoöversätt'),
translatePage:T('翻译本页','翻譯本頁','Translate','翻訳','번역','Traduire','Übersetzen','Traducir','Traduzir','Перевести','ترجمة','अनुवाद','แปล','Dịch','Traduci','Vertalen','Tłumacz','Çevir','Terjemahkan','Översätt'),
translated:T('已翻译','已翻譯','Translated','翻訳済','번역됨','Traduit','Übersetzt','Traducido','Traduzido','Переведено','مترجم','अनुवादित','แปลแล้ว','Đã dịch','Tradotto','Vertaald','Przetłumaczono','Çevrildi','Diterjemahkan','Översatt'),
translating:T('翻译中…','翻譯中…','Translating…','翻訳中…','번역 중…','Traduction…','Übersetze…','Traduciendo…','Traduzindo…','Перевод…','جارٍ الترجمة…','अनुवाद हो रहा…','กำลังแปล…','Đang dịch…','Traduzione…','Bezig met vertalen…','Tłumaczenie…','Çevriliyor…','Menerjemahkan…','Översätter…'),
canceled:T('翻译已取消','翻譯已取消','Translation canceled','翻訳キャンセル','번역 취소됨','Traduction annulée','Übersetzung abgebrochen','Traducción cancelada','Tradução cancelada','Перевод отменен','تم إلغاء الترجمة','अनुवाद रद्द','ยกเลิกการแปล','Đã hủy dịch','Traduzione annullata','Vertaling geannuleerd','Anulowano tłum.','Çeviri iptal edildi','Terjemahan dibatalkan','Översättning avbruten'),
noText:T('未找到可翻译文本','未找到可翻譯文本','No translatable text','翻訳可能なテキストなし','번역 가능한 텍스트 없음','Aucun texte traduisible','Kein übersetzbarer Text','Sin texto traducible','Sem texto traduzível','Нет текста','لا يوجد نص قابل للترجمة','अनुवाद योग्य पाठ नहीं','ไม่มีข้อความที่แปลได้','Không có văn bản','Nessun testo traducibile','Geen vertaalbare tekst','Brak tekstu','Çevrilecek metin yok','Tidak ada teks','Ingen översättbar text'),
noKey:T('请先配置 API Key','請先配置 API Key','Configure API Key','APIキーを設定してください','API 키 설정 필요','Configurer clé API','API-Schlüssel konfigurieren','Configurar API Key','Configurar Chave API','Настроить API','تكوين مفتاح API','API कुंजी कॉन्फ़िगर करें','ตั้งค่า API Key','Cấu hình API Key','Configura chiave API','API-sleutel configureren','Skonfiguruj klucz API','API Anahtarını Yapılandır','Konfigurasi API Key','Konfigurera API-nyckel'),
completed:T('翻译完成','翻譯完成','Translation complete','翻訳完了','번역 완료','Traduction terminée','Übersetzung abgeschlossen','Traducción completa','Tradução concluída','Перевод завершен','اكتملت الترجمة','अनुवाद पूर्ण','แปลเสร็จ','Dịch xong','Traduzione completata','Vertaling voltooid','Tłumaczenie gotowe','Çeviri tamamlandı','Terjemahan selesai','Översättning klar'),
failed:T('失败','失敗','failed','失敗','실패','échec','fehlgeschlagen','falló','falhou','Ошибка','فشل','विफल','ล้มเหลว','thất bại','fallito','mislukt','niepowodzenie','başarısız','gagal','misslyckades'),
segments:T('段','段','segments','件','개','segments','Segmente','segmentos','segmentos','сегментов','مقاطع','खंड','ส่วน','đoạn','segmenti','segmenten','segmenty','bölüm','segmen','segment'),
settings:T('翻译设置','翻譯設定','Settings','設定','설정','Paramètres','Einstellungen','Ajustes','Configurações','Настройки','الإعدادات','सेटिंग्स','ตั้งค่า','Cài đặt','Impostazioni','Instellingen','Ustawienia','Ayarlar','Pengaturan','Inställningar'),
history:T('历史token用量','歷史token用量','Token History','トークン履歴','토큰 기록','Historique des jetons','Token-Verlauf','Historial de Tokens','Histórico de Tokens','История токенов','سجل الرموز','टोकन इतिहास','ประวัติโทเค็น','Lịch sử Token','Cronologia token','Token Geschiedenis','Historia tokenów','Token Geçmişi','Riwayat Token','Tokenhistorik'),
clearCache:T('清除缓存','清除快取','Clear Cache','キャッシュ削除','캐시 삭제','Vider le cache','Cache leeren','Limpiar Caché','Limpar Cache','Очистить кэш','مسح الذاكرة المؤقتة','कैश साफ़ करें','ล้างแคช','Xóa Cache','Cancella cache','Cache wissen','Wyczyść pamięć','Önbelleği Temizle','Hapus Cache','Rensa cache'),
cacheCleared:T('缓存已清除','快取已清除','Cache cleared','キャッシュ削除済','캐시 삭제됨','Cache vidé','Cache geleert','Caché limpiada','Cache limpo','Кэш очищен','تم المسح','कैश साफ़ हुआ','ล้างแคชแล้ว','Đã xóa Cache','Cache cancellata','Cache gewist','Pamięć wyczyszczona','Önbellek temizlendi','Cache dihapus','Cache rensad'),
pageTokens:T('本页token消耗','本頁token消耗','Page tokens','ページトークン','페이지 토큰','Jetons de page','Seiten-Token','Tokens de página','Tokens da página','Токены страницы','رموز الصفحة','पृष्ठ टोकन','โทเค็นหน้า','Token trang','Token pagina','Paginatokens','Tokeny strony','Sayfa tokenları','Token halaman','Sidtoken'),
hitRate:T('缓存命中率','快取命中率','Cache hit rate','キャッシュヒット率','캐시 적중률','Taux de succès du cache','Cache-Trefferquote','Tasa de aciertos','Taxa de acerto do cache','Попадания в кэш','معدل الوصول للذاكرة','कैश हिट दर','อัตราแคชฮิต','Tỉ lệ cache','Tasso di hit cache','Cache hitratio','Trafność pamięci','Önbellek isabet oranı','Rasio cache','Cacheträffar'),
langSwitch:T('语言切换至','語言切換至','Language:','言語変更:','언어 변경:','Langue :','Sprache:','Idioma:','Idioma:','Язык:','اللغة:','भाषा:','ภาษา:','Ngôn ngữ:','Lingua:','Taal:','Język:','Dil:','Bahasa:','Språk:'),
cacheClearedSwitch:T('，缓存已清除','，快取已清除',', cache cleared','、キャッシュ削除済',', 캐시 삭제됨','cache vidé','Cache geleert','caché limpiada','cache limpo','кэш очищен','تم مسح الذاكرة المؤقتة','कैश साफ़ हुआ','ล้างแคชแล้ว','đã xóa cache','cache cancellata','cache gewist','pamięć wyczyszczona','önbellek temizlendi','cache dihapus','cache rensad'),
input:T('输入','輸入','Input','入力','입력','Entrée','Eingabe','Entrada','Entrada','Ввод','الإدخال','इनपुट','อินพุต','Đầu vào','Input','Invoer','Wejście','Giriş','Masukan','Indata'),
output:T('输出','輸出','Output','出力','출력','Sortie','Ausgabe','Salida','Saída','Вывод','الإخراج','आउटपुट','เอาต์พุต','Đầu ra','Output','Uitvoer','Wyjście','Çıkış','Keluaran','Utdata'),
total:T('总计','總計','Total','合計','합계','Total','Gesamt','Total','Total','Всего','المجموع','कुल','รวม','Tổng','Totale','Totaal','Razem','Toplam','Total','Totalt'),
estCost:T('预估费用','預估費用','Est. cost','推定費用','예상 비용','Coût estimé','Geschätzte Kosten','Costo est.','Custo estimado','Ориент. стоимость','التكلفة التقريبية','अनुमानित लागत','ค่าใช้จ่ายโดยประมาณ','Chi phí ước tính','Costo stimato','Geschatte kosten','Szac. koszt','Tah. maliyet','Perkiraan biaya','Beräknad kostnad'),
cacheEntries:T('缓存条目','快取條目','Cache entries','キャッシュ項目','캐시 항목','Entrées du cache','Cache-Einträge','Entradas de caché','Entradas de cache','Записей в кэше','إدخالات الذاكرة','कैश प्रविष्टियाँ','รายการแคช','Mục cache','Voci cache','Cache-items','Wpisy pamięci','Önbellek girişleri','Entri cache','Cacheposter'),
restored:T('已还原原文','已還原原文','Original restored','原文に戻した','원문 복원됨','Original restauré','Original wiederhergestellt','Original restaurado','Original restaurado','Оригинал восстановлен','تمت استعادة الأصل','मूल पुनर्स्थापित','คืนค่าต้นฉบับแล้ว','Đã khôi phục gốc','Originale ripristinato','Origineel hersteld','Przywrócono oryginał','Orijinal geri yüklendi','Asli dipulihkan','Original återställt'),
autoDetect:T('自动检测','自動檢測','Auto Detect','自動検出','자동 감지','Détection auto','Automatisch erkennen','Detectar auto.','Detecção Automática','Автоопределение','كشف تلقائي','स्वतः पहचान','ตรวจจับอัตโนมัติ','Tự động phát hiện','Rilevamento automatico','Automatisch detecteren','Auto wykrywanie','Otomatik Algıla','Deteksi Otomatis','Autodetektera'),
source:T('源语种','源語種','Source','ソース','소스','Source','Quelle','Origen','Origem','Исходный','المصدر','स्रोत','ต้นทาง','Nguồn','Sorgente','Bron','Źródło','Kaynak','Sumber','Källa'),
target:T('目标语种','目標語種','Target','ターゲット','타겟','Cible','Ziel','Destino','Destino','Целевой','الهدف','लक्ष्य','ปลายทาง','Đích','Destinazione','Doel','Cel','Hedef','Target','Mål'),
autoShort:T('自动','自動','Auto','自動','자동','Auto','Auto','Auto','Auto','Авто','تلقائي','स्वतः','อัตโนมัติ','Tự động','Auto','Auto','Auto','Otomatik','Otomatis','Auto'),
};
